---
title: "Leguminosae: states and fates of the Brazilian flora conservation"
author: 
  - L.S.B. Jordão
  - Amorim, E.T.
  - Aragão, L.A.
  - Bicalho, M.B.
  - Calfo, V.
  - Ferreira, G.C.
  - Gomes, M.
  - Mello, P.H.A.
  - Wimmer, F.C.
  - Fernandez, E.
  - et al.
lang: pt
format:
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
abstract: "Brazil is home to a significant proportion of Leguminosae species, comprising 13.5% of the global total. Furthermore, 51% of these species are endemic to the country, representing 7% of the worldwide Leguminosae diversity. Of the 3,068 species in Brazil, 1,024 (33%) underwent conservation assessments, carried out collaboratively with numerous specialists partnered with CNCFlora/JBRJ. Among the assessed species, 73% were not deemed threatened, including 56% classified as Least Concern (LC), 12% as Data Deficient (DD), and 5% as Near Threatened (NT). However, 277 (26%) are facing the risk of extinction, with 154 (5%) categorized as Endangered (EN), 81 (2.6%) as Vulnerable (VU), and 42 (1.3%) as Critically Endangered (CR). Most of threatened species belong to the genus *Mimosa* (23%), followed by *Swartzia* (14%) and *Chamaecrista* (10%). Most of the threatened species consist of trees (49%), followed by shrubs (30%). Among phytogeographic domains, the Atlantic Forest is home to 119 (43%) threatened species, followed by the Cerrado with 78 (28%) species. If we focus on combined characteristics such as habit and phytogeographic domain, *Swartzia* stands out in first place in the Amazon and among trees species, followed by *Peltogyne*, *Inga*, and *Tachigali*. Half of the genus *Muellera* (10 spp.), predominantly composed of tree species, are considered threatened. If we consider the vegetation type, dense ombrophilous rainforest emerges in first place with 100 (36%) species, followed by campos rupestres with 54 (20%) species. Among the Brazilian states, Bahia (17%), Minas Gerais (15%), Rio de Janeiro (11%), Goiás (10%), and Amazonas (8%) stand out as the top five with the highest number of threatened species. However, it is important to note that a significant 71% of all threatened species are endemic to a single state, highlighting the crucial role of state-level engagement in developing effective policies for the protection of threatened species. Criterion B, encompassing EOO (Extent of Occurrence), AOO (Area of Occupancy), number of locations, and continuous decline, has been extensively employed, accounting for 91% of the assessments conducted. This is partly due to the substantial scarcity of population and reproductive data. However, the availability of historical land cover classification data from the MapBiomas initiative has prompted efforts to utilize this information as primary data for analyzing parameters of continuous decline and determining location counts. Now, we can leverage land evolution data to accurately quantify the magnitude of threats that confront a species. There is much more to explore when it comes to analyzing and integrating various data sources, employing data modeling techniques, and creating informative presentations. However, the true potential lies in the development of robust information systems that offer scalability, enabling us to effectively handle vast and decentralized datasets. By implementing such systems, we can automate the monitoring process of available data sets on taxon distribution and prioritize conservation actions. This enables the establishment of an objective framework for comprehensively monitoring the entire biota."
keywords: ["Fabaceae", "IUCN", "MapBiomas", "scalability", "threatened"]
---


# Slide 1

- Good day, everyone! My name is Lucas, and I'm delighted to be here today to present an overview and discuss the current status and future prospects of Brazilian Legumes conservation.

# Slide 2

- Brazil is home to 3,068 species of Leguminosae. 51% of these species are endemic to the country, representing 7% of the worldwide Leguminosae diversity.

# Slide 3

- 33% of Brazilian Legumes species underwent conservation assessments, that were conducted collaboratively with the valuable participation of numerous specialists who partnered with CNCFlora/JBRJ.

# Slide 4 - 5

- Let's take a closer look at the progress we have made in each genus within the Leguminosae family.

- With this chart, we have a good ideia of our progress.

# Slide 9

- Among the assessed species, 73% were not deemed threatened.

# Slide 11

- However, 277 are facing extinction risk.

# Slide 12

- Let's take a closer look only on the threatened species...

# Slide 14

- *Mimosa* is the champion genus in number of species and also in threatened species.

# Slide 21

- Among phytogeographic domain, Atlantic Forest is where we found more threatened species, and *Inga* is the genus with more threatened species.

# Slide 23

- In Cerrado (the Brazilian savanna), *Chamaecrista* stands out as the genus with the highest number of threatened species. Most of these species are from rupestrian grasslands.

# Slide 25

- In its turn, in Amazon, *Swartzia* stands out as the genus with the highest number of threatened species.

 
[click on '(phytogeographic domain)' = 'Caatinga']

[click on '(phytogeographic domain)' = 'Pampa']

[click on '(phytogeographic domain)' = 'Pantanal']


# UCs

- [click on 'is in UCs' = 'False']

- 105 species considered threatened are not protected in any conservation unit.

- [click on UCs from Bahia (APA Costa de Itacaré, Rebio Una, APA Lagoa Encantada, Refúgio da Vida Silvestre de Una, APA Baía de Camamu)]

# MapBiomas

- With the help of MapBiomas data, we can leverage land evolution data to accurately quantify the magnitude of threats that confront a species.

- *Luetzelburgia amazonica* 

# Bull-CNCFlora

- We emphasize the crucial importance of establishing robust information systems to automate biodiversity monitoring.

- We are building an objective framework for comprehensively monitor the entire Brazilian biota.

- The implementation of these systems facilitates scalability in assessments of extinction risk.

- Here is the front-end of Bull-CNCFlora, an application designed to facilitate the scaling-up of conservation assessments for Brazilian species.

- The Bull-CNCFlora utilizes a powerful queue system that manage background jobs, guaranteeing efficiency and asynchronous execution of workflows, in which we can chain processes, easy monitoring of progress and catch errors, to ensure a smooth data processing experience.

- The technology stack employed in the development of this application is based on JavaScript and TypeScript languages operating within the NodeJS environment.

- Under the hood, our backend infrastructure is built on the powerful and widely adopted NestJS framework.

- NestJS integrates the Bull framework to implement a queue system, while bull-board creates a user-friendly interface based on the React framework.

- For calculations of land cover evolution, we have successfully integrated Google Earth Engine into our NodeJS workflow using its client API. This integration enables us to leverage the advanced cloud processing capabilities of Google Earth Engine, allowing us to process the time series data obtained from all MapBiomas plataforms.

# Acknowledgment

- On behalf of CNCFlora, we express our deep gratitude to all taxonomists who have collaborated and continue to collaborate with CNCFlora. Your dedication and expertise are crucial to the conservation of life.